<?php

namespace AppBundle\Repository;

/**
 * MapZoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapZoneRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAnotherMapZone($playerZoneId) {
        $zones = $this->createQueryBuilder('mz')
            ->where('mz.id <> :player_zone_id')
                ->setParameter('player_zone_id', $playerZoneId)
            ->getQuery()
            ->getResult();

        return array_rand($zones, 1);
    }
}
