<?php

namespace AppBundle\Repository;

/**
 * PlayerCharacterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerCharacterRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $playerCharacterId
     * @param $tradeSkillId
     *
     * @return bool
     */
    public function hasRequiredTradeSkill($playerCharacterId, $tradeSkillId)
    {
         $result = $this->createQueryBuilder('pc')
             ->select('count(distinct(pc.id))')
             ->innerJoin('pc.tradeSkills', 'ts')
             ->where('pc.id = :player_character_id')
                 ->setParameter('player_character_id', $playerCharacterId)
             ->andWhere('ts.id = :trade_skill_id')
                 ->setParameter('trade_skill_id', $tradeSkillId)
             ->getQuery()
             ->getSingleScalarResult();

        return ($result > 0);
    }
}
