<?php

namespace AppBundle\Repository;

/**
 * PlayerCharacterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerCharacterRepository extends \Doctrine\ORM\EntityRepository
{
}
