<?php

namespace AppBundle\Repository;

/**
 * TradeSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TradeSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
