# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    actions:
        class: AppBundle\Services\Actions
        arguments:
          - "@doctrine.orm.default_entity_manager"
          - '@session'
    weapon_crafting:
        class: AppBundle\Services\SwordCrafting
        arguments:
          - '@workflow.weapon_crafting'
          - '@validator'
          - '@session'
          - '@actions'
    validator.weapon_crafting.has_been_taught:
        class: AppBundle\Validator\SwordCrafting\HasBeenTaughtValidator
        arguments:
          - "@doctrine.orm.default_entity_manager"
        tags:
          - { name: validator.constraint_validator, alias: weapon_crafting_has_been_taught_validator }
    validator.weapon_crafting.is_recipe_learned:
        class: AppBundle\Validator\SwordCrafting\IsRecipeLearnedValidator
        arguments:
          - '@session'
        tags:
          - { name: validator.constraint_validator, alias: weapon_crafting_is_recipe_learned_validator }
    validator.weapon_crafting.is_iron_collected:
        class: AppBundle\Validator\SwordCrafting\IsIronCollectedValidator
        arguments:
          - '@session'
        tags:
          - { name: validator.constraint_validator, alias: weapon_crafting_is_iron_collected_validator }
    validator.weapon_crafting.is_leather_bought:
        class: AppBundle\Validator\SwordCrafting\IsLeatherBoughtValidator
        arguments:
          - "@doctrine.orm.default_entity_manager"
        tags:
          - { name: validator.constraint_validator, alias: weapon_crafting_is_leather_bought_validator }
    player_vs_enemy:
        class: AppBundle\Services\PlayerVsEnemy
        arguments:
          - '@sm.factory'
          - '@doctrine.orm.default_entity_manager'
          - '@actions'
          - '@session'
