framework:
    workflows:
        weapon_crafting:
            marking_store:
                type: property_accessor
            supports:
                - AppBundle\Entity\Item
            # list of possible places
            places:
                - draft
                - trade_skill_learned
                - learning_recipe
                - recipe_known
                - collecting_iron
                - iron_ready
                - asking_for_leather
                - leather_ready
                - crafted
            # list of possible transitions
            transitions:
                knowledge_acquired:
                    from: draft
                    to: trade_skill_learned
                craft_it:
                    from: trade_skill_learned
                    to:
                      - learning_recipe
                      - collecting_iron
                      - asking_for_leather
                reciper_learned:
                    from: learning_recipe
                    to: recipe_known
                iron_collected:
                    from: collecting_iron
                    to: iron_ready
                leather_bought:
                    from: asking_for_leather
                    to: leather_ready
                craft:
                    from:
                      - recipe_known
                      - iron_ready
                      - leather_ready
                    to: crafted